# Generated by Django 5.2.6 on 2025-09-30 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuetrack', '0002_category_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='industry',
            field=models.CharField(blank=True, choices=[('Technology', 'Technology'), ('Finance', 'Finance'), ('Healthcare', 'Healthcare'), ('Education', 'Education'), ('Retail', 'Retail'), ('Engineering', 'Engineering'), ('Automotive', 'Automotive'), ('Food & Beverage', 'Food & Beverage'), ('Media & Entertainment', 'Media & Entertainment'), ('Construction', 'Construction'), ('Manufacturing', 'Manufacturing'), ('Food & Beverage', 'Food & Beverage'), ('Telecommunications', 'Telecommunications'), ('Education', 'Education'), ('Hospitality', 'Hospitality'), ('Real Estate', 'Real Estate'), ('Transportation & Logistics', 'Transportation & Logistics'), ('Energy & Utilities', 'Energy & Utilities'), ('Non-Profit', 'Non-Profit'), ('Other', 'Other')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='valuetrack.service')),
            ],
        ),
    ]
