# Generated by Django 5.2.6 on 2025-10-03 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuetrack', '0005_provider_solution_providers_solutionprovider'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='valuetrack.problem'),
        ),
    ]
